### ISSUE TITLE
Discord Server Link Expired. No Sign of Getting Updated Either.

### ISSUE THREAD

**Issue by ghost** [xNarnia/TCR-TerrariaChatRelay-TShock#3]
I see no possible way to join the discord support server as all existing links are currently expired. This seems have been an issue almost a year and i would hope someone would uptdate the link soon.

**Comment by xNarnia** [comment]
I wasn't around to maintain the server, so I didn't keep up with it. Here is an updated link now that I'm back!
https://discord.gg/xAQGT4VetN
