### ISSUE TITLE
The world does not even start.

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [xNarnia/TCR-TerrariaChatRelay-TShock#5]
It says "Loading Failed! No backup found."

It refused to load the world at that point. rolling back to previous version made the server functional again.

**Comment by xNarnia** [comment]
Going to look into this tonight. Thank you for reporting this! Just to grab more info...
- Is this on Windows or Linux?

**Comment by cheeeeeeeeeen** [comment]
The server is a Linux server.

**Comment by xNarnia** [comment]
Thank you. I'll be taking a look at this today for Linux

**Comment by xNarnia** [comment]
Can you please provide a list of mods that you are using on the server currently? This will help debug the issue for me.

We also have a Discord if you would like to participate in an open dialogue about the issue. Here is the link if you're interested.
https://discord.gg/xAQGT4VetN

**Comment by cheeeeeeeeeen** [comment]
```json
[
  "AutoReroll",
  "AutoTrash",
  "BetterBuffs",
  "BossChecklist",
  "BossCursor",
  "CalamityBossRushWeaponAdjustments",
  "CalamityMod",
  "CalamityModMusic",
  "CheatSheet",
  "ChensGradiusMod",
  "ClamExtraMusic",
  "CMusicPlanet",
  "DaisReforges",
  "DBZMOD",
  "DeathSpectate",
  "FunctionalBlockSwap",
  "HamstarHelpers",
  "HelpfulHotkeys",
  "HEROsMod",
  "ItemControl",
  "LansAutoJoinTeam",
  "LansUnlimitedBuffSlots",
  "LosingIsFun",
  "LowHealthBeep",
  "MagicStorage",
  "MaxStackPlus",
  "MinionCrits",
  "MoreAccessories",
  "RecipeBrowser",
  "ShopExpander",
  "SmartDoors",
  "SummonersAssociation",
  "TerrariaChatRelay",
  "WheresMyItems",
  "WingSlot",
  "x1526modDifficultBuff"
]
```

**Comment by xNarnia** [comment]
Fixed https://github.com/xPanini/TCR-TerrariaChatRelay/commit/5e988a0f1b2c133f782d9fc04eba27352573bd20
